#本地（开发环境）配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3312/test_spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1234Ab..
  jpa:
    show_sql: true
server:
  port: 8080
