spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    #type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 2
    min-idle: 2
    max-active: 2000
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 300000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 600000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: true
    test-on-return: true
 # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
        ddl-auto: update
    open-in-view: true
  thymeleaf:
    mode: LEGACYHTML5
app:
  customFields: '{"appname":"my_webservice"}' # 指定els索引 需小写
  logstashUrl: 10.19.248.200:31507